medweb_mapping:
  columns:
    date: Datum
    activity: Beschreibung der Aktivit√§t
    employee_name: Name des Mitarbeiters
    employee_code: Code des Mitarbeiters
  rules:
  - match: Privat Specialist Shift
    type: shift
    label: Privat Specialist Shift
    times:
      default: 08:00-16:00
    skill_overrides:
      privat_ct: 1
  - match: Generalist Support Shift
    type: shift
    label: Generalist Support Shift
    times:
      default: 08:00-16:00
    skill_overrides:
      all: 0
balancer:
  hours_counting:
    shift_default: true
    gap_default: false
worker_roster: {}
